### PR TITLE
Rebase on sm 3.0.12-6

### PR DESCRIPTION
**Pull request by Wescoeur**
Blocked by: https://github.com/xcp-ng-rpms/sm/pull/33
Not yet tested.

Koji build (v8.3-incoming, scratch): http://koji.xcp-ng.org/taskinfo?taskID=45618

### CODE REVIEW

**Review by ydirson — COMMENTED** [review]
"Import sm 8.2 LINSTOR fixes on 8.3" is a bit of a misnomer: it is a refresh of the patch series, including 8.2 LINSTOR fixes as well as 3 new patches.

otherwise LGTM

**Comment by stormi** [comment]
The PR now needs a rebase on master, since #33 was merged.

**Comment by Wescoeur** [comment]
Rebased.
New koji build (v8.3-incoming, scratch): http://koji.xcp-ng.org/taskinfo?taskID=46038

**Review by stormi — APPROVED** [review]

**Comment by stormi** [comment]
Koji build (v8.3-u-stormi1): http://koji.xcp-ng.org/taskinfo?taskID=46183

**Pull request merged**
